Lesson1/Lesson1/Models/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lesson1.Models
{
    public class Person
    {
        [ScaffoldColumn(false)]
        public int Id { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Поле для обязательного заполнения")]
        [MinLength(2, ErrorMessage = "Минимальная длина не более 2 символа")]
        [MaxLength(32, ErrorMessage = "Максимальная длина не более 32 символа")]
        [Description("Ф.И.О.")]
        [Display(Name = "Ф.И.О.")]

        public string Name { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Поле для обязательного заполнения")]
        [Range(18,65,ErrorMessage = "Возраст введен неверно")]
        [Description("Возраст")]

        [Display(Name = "Возраст")]
        public int Age { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Поле для обязательного заполнения")]
        [MinLength(2, ErrorMessage = "Минимальная длина не более 2 символа")]
        [MaxLength(32, ErrorMessage = "Максимальная длина не более 32 символа")]
        [Description("Должность")]

        [Display(Name = "Должность")]
        public string Position{ get; set; } 
        [DataType(DataType.EmailAddress,ErrorMessage = "Неверный формат эмэйла")]
        public string Email { get; set; }
      

    }
}

Lesson1/Lesson1/Controllers/PeopleController.cs
using Lesson1.Models;
using Lesson1.Service;
using System.Collections.Generic;
using System.ComponentModel;
using System.Web.Mvc;

namespace Lesson1.Controllers
{
    public class PeopleController : Controller
    {

        PeopleService _ps = new PeopleService();

        //общий список людей
        public ActionResult PeopleList()
        {
            //экземпляр
            Person person = new Person();

            //проводники данных
            ViewBag.Name = _ps.GetAttribute("Name", person);
            ViewBag.Position = _ps.GetAttribute("Position", person);
            ViewBag.People = _ps.GetPeople();
            return View();
        }


        //детали о каждом
        public ActionResult PersonDetails(int id)
        {
            //ViewBag.PersonDetails = _ps.GetPerson(id);
            return View(_ps.GetPerson(id));
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public ActionResult Create()
        {

            return View();

        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Create(Person person)
        {
            if (!ModelState.IsValid)
            {
                return View(person);
            }

            _ps.AddPerson(person);
            return RedirectToAction("PeopleList");

        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public ActionResult Edit(int id)
        {

            return View(_ps.GetPerson(id));

        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Edit(Person person)
        {
            if (!ModelState.IsValid)
            {
                return View(person);
            }

            _ps.EditPerson(person);
            return RedirectToAction("PeopleList");

        }

        [Authorize(Roles = "admin")]
        public ActionResult Delete(Person person)
        {
            _ps.DeletePerson(person);
            return RedirectToAction("PeopleList");

        }
    }



}

Lesson1/Lesson1/Views/People/Create.cshtml
@model Lesson1.Models.Person

@{
    ViewBag.Title = "Create";
}

<h2>Создание</h2>

@using (Html.BeginForm("Create", "People", FormMethod.Post))
{

    @Html.EditorForModel()
    <br>
    <input class="btn btn-primary" type="submit" value="Cоздать" />
}
    <p><a class="btn btn-primary pull-right" href="/People/PeopleList">Назад к списку</a></p>

Lesson1/Lesson1/Views/People/Edit.cshtml
@model Lesson1.Models.Person

@{
    ViewBag.Title = "Edit";
}

<h2>Редактирование</h2>

@using (Html.BeginForm("Edit", "People", FormMethod.Post))
{

    @Html.EditorForModel()
    <br>
    <input class="btn btn-primary" type="submit" value="Cохранить" />

}

<p><a class="btn btn-primary pull-right" href="/People/PeopleList">Назад к списку</a></p>

Lesson1/Lesson1/Views/People/PeopleList.cshtml
@{
    ViewBag.Title = "Список сотрудников";
}

<h2>Список сотрудников</h2>

<p><a class="btn btn-primary pull-right" href="/People/Create">Добавить сотрудника</a></p>




@Html.Partial("_people", (IEnumerable<Lesson1.Models.Person>)ViewBag.People)

Lesson1/Lesson1/Views/People/PersonDetails.cshtml
@model Lesson1.Models.Person

@{
    ViewBag.Title = "О сотруднике";
}

<h2>Данные сотрудника</h2>


<div class="row">
    Ф.И.О.: @Html.Label(Model.Name)
</div>
<div class="row">
    Возраст: @Html.Label(Model.Age.ToString())
</div>
<div class="row">
    Должность: @Html.Label(Model.Position)
</div>
<div class="row">
    Email: @Html.Label(Model.Email)
</div>

<p><a class="btn btn-primary" href="/People/PeopleList">Назад к списку</a></p>

Lesson1/Lesson1/Views/People/_people.cshtml
@model IEnumerable<Lesson1.Models.Person>

<div class="table-responsive">
    <table class="table table-bordered table-condensed table-hover"
        <tr>
            <th>
                <h2>@ViewBag.Name</h2>
            </th>
            <th>
                <h2>@ViewBag.Position</h2>
            </th>
            <th>
                <h2>Возраст</h2>
            </th>
        </tr>
@foreach (var item in Model)
{
        <tr>
            <td>
                @Html.Label(item.Name)
            </td>
            <td>
                @Html.Label(item.Position)
            </td>
            <td>
                @Html.Label(item.Age.ToString())
            </td>
            <td>
                <input type="hidden" value="@ViewBag.PersonId" name="PersonId" />
                <a class="btn btn-primary" href="/People/PersonDetails/@item.Id">Показать</a>
            </td>
            <td>
                @Html.ActionLink("Редактировать", "Edit", "People", new { id = item.Id }, new { @class = "btn btn-primary" })
            </td>
            <td>
                @Html.ActionLink("Удалить", "Delete", "People", new { id = item.Id }, new { @class = "btn btn-danger" })
            </td>
        </tr>
}
  </table>
    </div>